# Generated by Django 3.0.5 on 2020-06-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Sanidhya', max_length=100),
            preserve_default=False,
        ),
    ]
